### ISSUE TITLE
Add ESP8266

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/micropython#8]
```[tasklist]
### Tasks
- [ ] Update scripts to verify board type (ESP8266 is WiFi only, can't run BLE scripts)
- [ ] Update docs to accommodate non-ESP32 board
- [ ] Add board info to **docs/boards.md**; refer to it in **docs/get_started.md** as needed
- [ ] What changes are needed, to **script/*.sh**? (Maybe **run.sh** wants to check board type?)
```

**Comment by solvaholic** [comment]
## ESP8266MOD
WiFi only.

The one I'm using looks a lot like this one, tho the labeling is different:
https://i.stack.imgur.com/d7Ykr.jpg

Looks like GPIO == D3

https://docs.micropython.org/en/latest/esp8266/tutorial/intro.html

What got this working? Ground GPIO0 and press RST. I think.
